### ISSUE TITLE
unable to download gene annotation

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [vanheeringen-lab/genomepy#102]
(gimme100) -bash-4.2$ genomepy install hg19 UCSC --annotation

Downloading annotation from http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/knownGene.txt.gz...
**invalid signed integer: ""**
Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/provider.py", line 402, in attempt_and_report
    self.download_and_generate_annotation(genomes_dir, link, localname)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/provider.py", line 374, in download_and_generate_annotation
    sp.check_call(cmd.format(pred_file, gtf_file), shell=True)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'genePredToGtf file /home/feuerste/.local/share/genomes/hg19/tmpml88v21a/hg19.annotation.gp /home/feuerste/.local/share/genomes/hg19/tmpml88v21a/hg19.annotation.gtf && gzip -f /home/feuerste/.local/share/genomes/hg19/tmpml88v21a/hg19.annotation.gtf' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme100/bin/genomepy", line 10, in <module>
    sys.exit(cli())
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/cli.py", line 209, in install
    **kwargs,
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/functions.py", line 270, in install_genome
    p.download_annotation(name, genomes_dir, localname=localname, **kwargs)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/provider.py", line 438, in download_annotation
    self.attempt_and_report(name, localname, link, genomes_dir)
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/genomepy/provider.py", line 405, in attempt_and_report
    f"\nCould not download annotation for {name} from {self.name}\n"
genomepy.exceptions.GenomeDownloadError:
Could not download annotation for hg19 from UCSC
If you think the annotation should be there, please file a bug report at:
https://github.com/vanheeringen-lab/genomepy/issues

**Comment by simonvh** [comment]
Can confirm! I get the same error. @siebrenf any idea why this is not caught by the current tests?

**Comment by siebrenf** [comment]
UCSC stores multiple gene annotation files. There appears to be an issue parsing the `knownGene.txt.gz` file. The other files work properly. 

@simonvh: testing did not catch this as our test genome only has another file.

@ClarissaFeuersteinAkgoz: Thank you for bringing this to our attention! I'll get on this :)
As a quick fix you can change the order in which we try to find annotation files. The code is in `genomepy/provider.py`. If you installed this with conda it should something like:
- go to ~/anaconda3/envs/YOUR_ENV_NAME/lib/python3.6/site-packages/genomepy/provider.py
- replace line 895 with `annot_files = ["ensGene.txt.gz", "knownGene.txt.gz", "refGene.txt.gz"]`
