### ISSUE TITLE
Pandas version 0.22 needed for 'sklearn.externals.six'? 

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [vanheeringen-lab/genomepy#105]
(gimme100) -bash-4.2$ gimme motifs TAp73alpha.bed -g hg19 -n gimme.p73 -a small                                                                                                                                                              -t Homer,MDmodule,BioProspector

Traceback (most recent call last):
  File "/home/feuerste/miniconda3/envs/gimme100/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimm                                                                                                                                                             emotifs/cli.py", line 11, in <module>
    from gimmemotifs import commands, __version__
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimm                                                                                                                                                             emotifs/commands/__init__.py", line 15, in <module>
    "{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], level
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimm                                                                                                                                                             emotifs/commands/maelstrom.py", line 9, in <module>
    from gimmemotifs.maelstrom import run_maelstrom
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimm                                                                                                                                                             emotifs/maelstrom.py", line 37, in <module>
    from gimmemotifs.moap import moap, Moap, scan_to_table
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/gimm                                                                                                                                                             emotifs/moap.py", line 41, in <module>
    from lightning.classification import CDClassifier
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/ligh                                                                                                                                                             tning/classification.py", line 1, in <module>
    from .impl.adagrad import AdaGradClassifier
  File "/home/feuerste/miniconda3/envs/gimme100/lib/python3.7/site-packages/ligh                                                                                                                                                             tning/impl/adagrad.py", line 8, in <module>
    from sklearn.externals.six.moves import xrange
**ModuleNotFoundError: No module named 'sklearn.externals.six'**

Unfortunaltely downgrading to pandas 0.22 did not solve my issue. Do you have an idea what could be the issue?

**Comment by siebrenf** [comment]
That's a gimme motifs issue. My guess would be a different version of sklearn is required.

@simonvh, any thoughts?

**Comment by ClarissaFeuersteinAkgoz** [comment]
scikit-learn downgraded to version 0.22 
worked I guess... hope

**Comment by simonvh** [comment]
It seems that a package that GimmeMotifs depends on is no longer maintained. I'll have to look into that later, solution for now indeed seems to be to use sklearn 0.22.
