### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by arogozhnikov** [vanheeringen-lab/genomepy#109]
Hi, please find logs below: (Python 3.6.9, ubuntu 18)

```
> pip3 install genomepy
Collecting genomepy
  Using cached genomepy-0.8.3.tar.gz (44 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ualk9qj9/genomepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ualk9qj9/genomepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-90hw6pin
         cwd: /tmp/pip-install-ualk9qj9/genomepy/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ualk9qj9/genomepy/setup.py", line 13, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18587: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by siebrenf** [comment]
Hey @arogozhnikov,

Sorry to hear about this! It seems the issue is caused when reading the `README.md`, which contains a non-ascii character. I found [a similar issue](https://github.com/facebookresearch/fastText/issues/833) which was solved by running `export LC_ALL=C.UTF-8` in the terminal before installing. Could you see if this works for you? If so, I'll also try their fix for the next version!

P.S. this is literally my fault. The non-ascii character is in my name :*(

**Comment by arogozhnikov** [comment]
> P.S. this is literally my fault. The non-ascii character is in my name :*(
lol. 

Yup, tried setting `LC_ALL` and installation was successful
