### ISSUE TITLE
issue with annotation in 0.12.0

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/genomepy#202]
```
2022-03-30 09:39:05 | ERROR | An error has been caught in function '<module>', process 'MainProcess' (29430), thread 'MainThread' (22359692490560):
Traceback (most recent call last):

> File "/vol/mbconda/heeringen/envs/ananse_5558b5f/bin/ananse", line 582, in <module>
    args.func(args)
    │    │    └ Namespace(binding='../binding/lung.binding/binding.h5', fin_expression=['/ceph/rimlsfnwi/data/moldevbio/share_moldevbio/heeri...
    │    └ <function network at 0x1453ea6be040>
    └ Namespace(binding='../binding/lung.binding/binding.h5', fin_expression=['/ceph/rimlsfnwi/data/moldevbio/share_moldevbio/heeri...
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/ananse/commands/network.py", line 34, in network
    b.run_network(
    │ └ <function Network.run_network at 0x1453e96f01f0>
    └ <ananse.network.Network object at 0x1453e94768e0>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/ananse/network.py", line 587, in run_network
    expression = self.gene_overlap(expression, tfs)
                 │    │            │           └ ['IRF5', 'TFEB', 'THAP11', 'NR3C1', 'GRHL1', 'EBF3', 'E2F5', 'CREB1', 'TGIF2LX', 'NKX3-1', 'GCM1', 'BCL6B', 'SIM1', 'TFAP2C',...
                 │    │            └            expression
                 │    │              target_id
                 │    │              A1BG              0.2
                 │    │              A1CF              0.0
                 │    │              A2M            1920.7
                 │    │              A2ML1          ...
                 │    └ <function Network.gene_overlap at 0x1453e96f0280>
                 └ <ananse.network.Network object at 0x1453e94768e0>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/ananse/network.py", line 694, in gene_overlap
    bed_genes = set(gp.genes())
                    │  └ <function Annotation.genes at 0x1453fd6808b0>
                    └ <genomepy.annotation.Annotation object at 0x1453e9446f10>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/genomepy/annotation/__init__.py", line 195, in genes
    return list(set(self.named_gtf.index))
                    │    └ None
                    └ <genomepy.annotation.Annotation object at 0x1453e9446f10>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/genomepy/annotation/__init__.py", line 115, in __getattribute__
    val = self.gtf.join(
          │    └ None
          └ <genomepy.annotation.Annotation object at 0x1453e9446f10>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/genomepy/annotation/__init__.py", line 110, in __getattribute__
    _check_property(self.annotation_gtf_file, f"{self.name}.annotation.gtf")
    │               │    └ None
    │               └ <genomepy.annotation.Annotation object at 0x1453e9446f10>
    └ <function _check_property at 0x1453fe995670>
  File "/vol/mbconda/heeringen/envs/ananse_5558b5f/lib/python3.9/site-packages/genomepy/annotation/utils.py", line 44, in _check_property
    raise FileNotFoundError(f"'{fname}' required.")

FileNotFoundError: 'hg38.genes.annotation.gtf' required.
```

**Comment by simonvh** [comment]
Is this a genompy issue or a ANANSE-genomepy crossover issue?

**Comment by siebrenf** [comment]
`genomepy.Annotation.genes()` now uses the GTF to return `gene_name`s by default, instead of using the BED to return `transcript_id`s. 

I've fixed the code in ANANSE (should work with any genomepy version).
