### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by oriolfornes** [vanheeringen-lab/genomepy#226]
Hi, I have been using genomepy for a while now, but I have suddenly been getting this error:

```
(explainn) genomepy clean
All clean!
(explainn) genomepy search human
08:46:22 | INFO | Downloading assembly summaries from GENCODE
08:46:47 | INFO | Downloading assembly summaries from UCSC
Traceback (most recent call last):
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 263, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Lost connection to MySQL server at 'reading initial communication packet', system error: 104

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/bin/genomepy", line 10, in <module>
    sys.exit(cli())
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/cli.py", line 411, in search
    for row in genomepy.search(term, provider, size):
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/__init__.py", line 131, in search
    for p in online_providers(provider):
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/__init__.py", line 104, in online_providers
    yield create(provider)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/__init__.py", line 60, in create
    return p()
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/gencode.py", line 42, in __init__
    self.ucsc = UcscProvider()
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/ucsc.py", line 51, in __init__
    self.genomes = get_genomes("http://api.genome.ucsc.edu/list/ucscGenomes")
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/diskcache/core.py", line 1877, in wrapper
    result = func(*args, **kwargs)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/ucsc.py", line 419, in get_genomes
    genomes = add_accessions1(genomes)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/ucsc.py", line 446, in add_accessions1
    df = pd.DataFrame.from_records(ret)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/pandas/core/frame.py", line 2296, in from_records
    first_row = next(data)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/genomepy/providers/ucsc.py", line 515, in query_ucsc
    cnx = mysql.connector.connect(
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/mysql/connector/pooling.py", line 286, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 101, in __init__
    self.connect(**kwargs)
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1095, in connect
    self._open_connection()
  File "/mnt/common/WassermanLab/miniconda3/envs/explainn/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 268, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.OperationalError: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104
```

**Comment by oriolfornes** [comment]
I upgradead the package to the latest version using pipy and now it works.
