### ISSUE TITLE
missing url for hg19 blacklist file

### ISSUE THREAD

**Issue by joonan30** [vanheeringen-lab/genomepy#63]
Hi 

Thanks for the tool. It seems that the link for hg19 blacklist bed is missing. The current download path is set to `http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/hg38-human/hg19.blacklist.bed.gz` but no file can be found.

```
genomepy install hg19 UCSC             
Downloading blacklist http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/hg38-human/hg19.blacklist.bed.gz
Traceback (most recent call last):
  File "/Users/joonan/Library/Python/3.7/lib/python/site-packages/genomepy/plugins/blacklist.py", line 33, in after_genome_download
    response = urlopen(link)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by simonvh** [comment]
@joonan30 sorry for that! This will be fixed in the next release.
