### ISSUE TITLE
Please provide genomes_dir error after upgrade to 0.8.1

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/genomepy#87]
In the config `genome_dir` seems to be renamed to `genomes_dir`. When I upgrade my genomepy version it does not add `genomes_dir` to the config, and gives me this error.
```
Traceback (most recent call last):
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/bin/genomepy", line 10, in <module>
    sys.exit(cli())
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/cli.py", line 195, in install
    genomepy.install_genome(
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/functions.py", line 256, in install_genome
    generate_env()
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/functions.py", line 154, in generate_env
    for env in generate_exports():
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/functions.py", line 120, in generate_exports
    for name in list_installed_genomes():
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/functions.py", line 104, in list_installed_genomes
    genomes_dir = get_genomes_dir(genomes_dir, check_exist=False)
  File "/home/sande/anaconda3/envs/test-snakemake-wrappers/lib/python3.8/site-packages/genomepy/utils.py", line 231, in get_genomes_dir
    raise exceptions.ConfigError("Please provide or configure a genomes_dir")
norns.exceptions.ConfigError: Please provide or configure a genomes_dir
```

Up to you to decide if you want to have `genomes_dir` existing in parallel to `genome_dir` for backward compatability, or you just overwrite it :)

The easy fix is for me is to add `genomes_dir` to `~/.config/genomepy/genomepy.yaml`.

**Comment by simonvh** [comment]
I think `genome_dir` should also still be valid. This means that `genomes_dir` will be the config file default for new installations, but `genomepy` should check for `genome_dir` if `genomes_dir` is not present. Maybe even add `genomes_dir` to the config.

**Comment by siebrenf** [comment]
oh dear, that is annoying! I did not consider that all the existing configs wont be updated...

Solutions:
- add a version number in the config, and update if mismatched
- check if the config is complete every time its used then
- version-specific config, similar to the version-specific bucketcache
I guess option 1 is the lightest solution... What do you think?

On the distinction:
`genome_dir` is the location of a specific genome, so it has no place in the config. 'genomes_dir` is the general file location, and should definitely be there. 

Thanks for mentioning! I'll look into it soon-ish :)

**Comment by Maarten-vd-Sande** [comment]
I think the ugliest but most user(read: me)-friendly way would be to have both `genome_dir` and `genomes_dir` in the config, or have version specific caches.

Not sure how many people use genomepy in their pipelines/processing environments, and how often this clash will occur. But for example: think about people using our pipeline, or gimmemotifs in an older version, parallel to a different environment with a new version of it. This will always clash unless you support both. 

I feel like the "professional"(for lack of a better word) solution  would be to support both in the config and start giving deprecationwarnings. But I am not sure how often people will encounter this and if it's worth the effort...  ¯\_(ツ)_/¯

**Comment by simonvh** [comment]
I think supporting both is the way forward for now. In the new version, `genomes_dir` will be used. However, if there is an old config present, genomepy should use the `genome_dir` variable.
